SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES,A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A
INNER JOIN REST_REVIEW AS B
ON A.REST_ID = B.REST_ID
WHERE SUBSTR(A.ADDRESS,1,2) = '서울'
GROUP BY A.REST_ID
ORDER BY SCORE DESC, A.FAVORITES DESC;


# SELECT A.REST_ID, B.REST_NAME, B.FOOD_TYPE, B.FAVORITES, B.ADDRESS, ROUND(AVG(A.REVIEW_SCORE),2) AS SCORE
# FROM REST_REVIEW A
# JOIN REST_INFO B ON A.REST_ID = B.REST_ID
# GROUP BY A.REST_ID
# HAVING B.ADDRESS LIKE '서울%'
# ORDER BY SCORE DESC, B.FAVORITES DESC